name: C++ Style Check

on:
    branches-ignore:
      - main
      - 'main*'
jobs:
  style-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate branch name and structure
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Branch name: $BRANCH_NAME"
          
          # Check branch name format: number followed by letter (e.g., 1A, 12B)
          if ! [[ "$BRANCH_NAME" =~ ^[0-9]+[A-Z]$ ]]; then
            echo "❌ Error: Branch name must be in format <number><letter> (e.g., 1A, 12B)"
            exit 1
          fi
          
          # Check if folder with same name exists
          if [ ! -d "$BRANCH_NAME" ]; then
            echo "❌ Error: Folder '$BRANCH_NAME' does not exist"
            exit 1
          fi
          
          # Check if main.cpp exists in the folder
          if [ ! -f "$BRANCH_NAME/main.cpp" ]; then
            echo "❌ Error: File '$BRANCH_NAME/main.cpp' does not exist"
            exit 1
          fi
          
          echo "✅ Branch structure validation passed"

      - name: Install clang tools
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq clang-format clang-tidy

      - name: Run clang-format check
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          FILE="$BRANCH_NAME/main.cpp"
          
          echo "Checking formatting for $FILE..."
          
          # Run clang-format and check for differences
          clang-format --style=file "$FILE" > /tmp/formatted.cpp
          
          if ! diff -u "$FILE" /tmp/formatted.cpp; then
            echo ""
            echo "❌ Error: Code is not properly formatted"
            echo "Run 'clang-format -i $FILE' to fix formatting"
            exit 1
          fi
          
          echo "✅ clang-format check passed"

      - name: Run clang-tidy check
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          FILE="$BRANCH_NAME/main.cpp"
          
          echo "Running clang-tidy on $FILE..."
          
          # Run clang-tidy with the config file
          if ! clang-tidy "$FILE" -- -std=c++17; then
            echo ""
            echo "❌ Error: clang-tidy found issues"
            exit 1
          fi
          
          echo "✅ clang-tidy check passed"
